### PR TITLE
Update faq.md

### PR DESCRIPTION
**Pull request by samleegithub**
Change answer to "When will Haveno be ready for use?" if FAQ from  end of 2022 to 2024.

### CODE REVIEW

**Comment by samleegithub** [comment]
@woodser @napoly Could you delete this pull request using this github virtual assistant link? I used the wrong github account. I will submit a new PR of the same change with my other account.

https://support.github.com/request?q=delete+a+pull+request

**Comment by woodser** [comment]
This PR is closed. Why take further action?

**Comment by samleegithub** [comment]
Didn't want to associate my work account with my reddit account

**Comment by woodser** [comment]
Ah gotcha. Ok I've submitted the request.

**Comment by samleegithub** [comment]
Perfect. Thank you!

**Pull request closed without merging**
