### PR TITLE
faq: add new entries and links to headers

### PR DESCRIPTION
**Pull request by erciccione**
(ignore the codacy warning, still needs to be set properly)

### CODE REVIEW

**Comment by erciccione** [comment]
Hey @proudmuslim-dev. If you have time could you review the wording in this PR? It would be very appreciated :)

**Comment by proudmuslim-dev** [comment]
> Hey @proudmuslim-dev. If you have time could you review the wording in this PR? It would be very appreciated :)

Sure thing! I'll read through it either today or tomorrow morning :)

**Comment by proudmuslim-dev** [comment]
@erciccione I've opened a [pull request](https://github.com/erciccione/haveno-site/pull/1/files) on your fork as suggesting the changes here would result in a lot of clutter & extra commits

**Comment by erciccione** [comment]
Thanks a lot @proudmuslim-dev! No worries about clutter in the future, github's review can be easily hidden and commits squashed :)

**Pull request merged**
